CREATETABLEusers (
    idSERIALPRIMARY KEY,
    usernameVARCHAR(100)NOT NULL,
    emailVARCHAR(150)UNIQUENOT NULL,
roleVARCHAR(50)DEFAULT'RESEARCHER',
    created_atTIMESTAMPDEFAULT CURRENT_TIMESTAMP
);

CREATETABLEdatasets (
    idSERIALPRIMARY KEY,
    user_idINTREFERENCES users(id)ON DELETE CASCADE,
nameVARCHAR(255)NOT NULL,
    data_typeVARCHAR(50)NOT NULLCHECK(data_typeIN ('CSV','DICOM')),
    is_cleansedBOOLEANDEFAULT false,
    uploaded_atTIMESTAMPDEFAULT CURRENT_TIMESTAMP
);

CREATETABLEtraining_jobs (
    idSERIALPRIMARY KEY,
    dataset_idINTREFERENCES datasets(id)ON DELETE CASCADE,
    job_uuidVARCHAR(100)UNIQUENOT NULL,
    epochsINTDEFAULT100,
statusVARCHAR(50)DEFAULT'QUEUED',
    privacy_scoreDECIMAL(5,2),
    started_atTIMESTAMPDEFAULT CURRENT_TIMESTAMP
);